### ISSUE TITLE
Отладочные выводы должны иметь метку времени и быть отключаемыми

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/Bot_Testik#11]
https://github.com/Pin4uck/Bot_Testik/blob/9312c0512ac968dcc1831eed53a83dac9fde7170/currency.py#L8

Для отладочных сообщений в Питоне есть модуль logging:

* https://webdevblog.ru/logging-v-python/
* https://habr.com/ru/post/513966/

Желательно, чтобы уровень подробности программа брала из переменной окружения, например, PYTHON_LOGGING.

Уровень по умолчанию = WARNING

**Comment by ilyaevseev** [comment]
Вижу b653633e3228280065a018691cba76e0bd3dc0e9

Есть три замечания:
* logging.basicConfig вызывается с фиксированным level=logging.DEBUG вместо настраиваемого через переменные окружения
* значением по умолчанию д.б не DEBUG, а WARNING
* большинство сообщений лучше выводить не через logging.info, а через logging.debug, потому что по смыслу они представляют интерес только во время отладки

**Comment by Pin4uck** [comment]
```python
TGBOT_LOGLEVEL = logging.DEBUG
TBLOG = os.getenv("TGBOT_LOGLEVEL")
logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', datefmt='%d-%b-%y %H:%M:%S', level=TBLOG)```
так вот пробовал - не проходит

**Comment by ilyaevseev** [comment]
Ищем в гугле: "python logging basicconfig os.getenv"

Тут же находим: https://stackoverflow.com/a/39794595/2743554

Должно быть что-то вроде:

```
loglevel = os.getenv("TGBOT_LOGLEVEL", logging.WARNING)
logging.basicConfig(format = "...", level = loglevel)
```

**Comment by Pin4uck** [comment]
Что-то я совсем не соображаю. Выдает ошибку
ValueError: Unknown level: 'logging.DEBUG'

**Comment by ilyaevseev** [comment]
Наверное, в переменной окружения должно быть не "logging.DEBUG", а просто "DEBUG".

Для общего понимания:
* logging.DEBUG - это целочисленная константа с именем DEBUG в библиотеке logging. Проверьте сами в командной строке Питона:
  ```
  >>> import logging ; print(logging.DEBUG)
  10  ```
* os.getenv всегда возвращает строку, убедитесь сами (в переменную окружения test я предварительно записал число):
  ```
  >>> import os ; a = os.getenv("test") ; print(a) ; print(type(a))
  123
  <class 'str'>
  ```
* logging.basicConfig в качестве параметра level понимает и целые числа (тип int - например, logging.DEBUG), и строки (тип str - например, "DEBUG").

**Comment by ilyaevseev** [comment]
Проверил - так не ругается:
```
import logging
logging.basicConfig(level = "DEBUG")
```

**Comment by ilyaevseev** [comment]
Кстати, можно попробовать не только так, как выше:
```
loglevel = os.getenv("TGBOT_LOGLEVEL", logging.WARNING)
logging.basicConfig(format = "...", level = loglevel)
```
Но и так:
```
loglevel = os.getenv("TGBOT_LOGLEVEL", "WARNING")
logging.basicConfig(format = "...", level = loglevel)
```
То есть чтобы везде были только строковые значения, и не было числовых значений с проблемами конвертации.

**Comment by Pin4uck** [comment]
А я думал, что обязательно logging нужно прописывать, напр.: logging.DEBUG.
Обновил файл. 
А по поводу сделать логирование отключаемым, это имелось ввиду занести значение в переменную окружения? Или нужно чтобы в самом коде можно было отключать?

**Comment by ilyaevseev** [comment]
logging нужно прописывать, если параметр не обрамлён в кавычки:

* В этом случае logging.DEBUG заменяется на значение переменной DEBUG  
  в библиотеке logging, т.е. на целочисленное значение 10.

logging не нужно прописывать, если параметр обрамлён в кавычки:
* В этом случае "DEBUG" является строковым значением.

logging.basicConfig умеет распознавать:
* как целочисленные значения (10, 20, ...),
* так и строковые ("DEBUG", "WARNING" и т.д.).

Сделать логирование отключаемым - это `loglevel = os.getenv("TGBOT_LOGLEVEL", "WARNING")`:
* переменная окружения TGBOT_LOGLEVEL не установлена -- вызовы logging.debug игнорируются, срабатывают только вызовы logging.warning и logging.error
* TGBOT_LOGLEVEL установлена и содержит INFO или DEBUG -- срабатывают все вызовы.

**Comment by Pin4uck** [comment]
14c611e87d91848436b6e3fbb59df4b88bcc1419

**Comment by ilyaevseev** [comment]
Считаем, что логирование Вы победили))
