### ISSUE TITLE
CACHE_AGE надо сделать конфигурируемым

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/Bot_Testik#12]
https://github.com/Pin4uck/Bot_Testik/blob/9312c0512ac968dcc1831eed53a83dac9fde7170/currency.py#L3

* Рекомендуемое значение по умолчанию - минимум 3600 (т.е. один час)
* Для отладки кэширования полезны значения в 10-15 секунд.
* Поэтому имеет смысл сделать значение конфигурируемым через переменные окружения.

### Например:

```
import os

CACHE_AGE = int(os.getenv("TGBOT_CACHE_MAXAGE", 3600))
```

### Набор переменных окружения для отладки можно сохранить в ENV-файл debug.env:

```
TGBOT_CACHE_MAXAGE=15
TGBOT_LOGLEVEL=DEBUG
```

### Загрузка ENV-файла:

* из PyCharm: https://stackoverflow.com/questions/42708389/how-to-set-environment-variables-in-pycharm
* из Linux CLI:
  ```
  ( set -o allexport && source debug.env && python3 MyProgram.py )
  ```

**Comment by Pin4uck** [comment]
Так я создал файл debag.env со значениями: TGBOT_CACHE_MAXAGE=15
TGBOT_LOGLEVEL=DEBUG
Я прописал в currency.py: 
import os
CACHE_AGE = int(os.getenv("TGBOT_CACHE_MAXAGE", 3600))
Но я не понимаю что должно происходить

**Comment by Pin4uck** [comment]
в репозитории я пока ни чего не менял

**Comment by ilyaevseev** [comment]
1. Не debag, а debug!
2. Описание os.getenv уже прочли?
3. В курсе, что такое переменные окружения? Если нет, то читайте https://ru.wikipedia.org/wiki/Переменная_среды

**Comment by Pin4uck** [comment]
Пока я не понимаю как оно конфигурируется, и что делать с этим файлом. и что именно вносить в пичарме в environment variables.

**Comment by ilyaevseev** [comment]
В environment variables в PyCharm надо внести:
* имя TGBOT_CACHE_MAXAGE - значение 15
* имя TGBOT_LOGLEVEL - значение DEBUG

Как именно вносить - см. картинки в https://stackoverflow.com/a/42708480/2743554 (ссылка на первый ответ в разделе, ссылку на который я давал выше)

Это вариант с раздельным добавлением и редактированием переменных окружения через диалоговые окна PyCharm.

Когда он получится, попробуем второй вариант - через Env-файл.

**Comment by Pin4uck** [comment]
Хорошо попробую через environment variables в PyCharm. Через файл вроде все работает

**Comment by Pin4uck** [comment]
Работает и через environment variables. Мне как-то нужно это отображать в репозитории?

**Comment by ilyaevseev** [comment]
В репозитории это уже отражено:
* 4bceeaac50b4b4929b2cd767263e7e39e6a4898d -- добавлен файл debug.env
* 5b87231dfc401b3ead8434d40af3215c1e0547c4 -- значения из переменных окружения читаются через os.getenv

Задачу можно считать решённой, закрываю.

Не забывайте всегда указывать в issue ссылки на исправляющие коммиты.
