### ISSUE TITLE
Надо использовать нашу функцию-обёртку dbcursor

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/Bot_Testik#13]
https://github.com/Pin4uck/Bot_Testik/blob/aa8779f2b228b341dbd3816e8c1c3fd07eb9de79/currency.py#L65

**Comment by Pin4uck** [comment]
исправил
https://github.com/Pin4uck/Bot_Testik/blob/3a34b0c12b658c17f2a638a04710ba407f3e978e/currency.py#L58

**Comment by ilyaevseev** [comment]
И тут же в следующей строке зачем-то:
```
curs = sqlite3.connect('currency.db')
```

**Comment by Pin4uck** [comment]
21c513320d9b13c7310d521f6ee4b474729faff4
Еще больше ошибок?
просто коммит не работает если вставить просто функцию-обёртку dbcursor. 
И возможно мой метод вышел не самым оптимальным

**Comment by ilyaevseev** [comment]
**Во-первых,** "dbconn = None" надо объявлять не внутри функции dbcursor, а в начале модуля.

Внутри функции переменная создаётся заново при каждом вызове функции и удаляется при её завершении.

И даже если переменная сохранялась после завершения функции, присвоение None затёрло бы запомненное с прошлого вызова значение.

**Во-вторых,** разве cursor нельзя использовать для insert/update + commit ? Я считал, что можно, но не проверял.

**Comment by Pin4uck** [comment]
pycharm ругается пишет что для коммит курсор не подходит.
"dbconn = None" - а с этим у меня был возник вопрос еще при изначальном написании, но я чет не спрашивал у Вас, If ругается если вынести его за пределы функции, и я не знал как правильно быть с этим

**Comment by ilyaevseev** [comment]
Ищите в гугле: "python global variables".

Например: https://www.geeksforgeeks.org/global-local-variables-python/

**Comment by Pin4uck** [comment]
8c10247f75e3001d41cd03768e46005ba7dfb40f
Вот немного наисправлял все то, чем был недоволен пичарм по PEP8

**Comment by ilyaevseev** [comment]
**Ошибка:** в read_cached_currency_rate перемудрили с вызовами "value = curs.fetchall()"

**Желательно:** чтобы коммит не был про всё на свете. Всё содержимое коммита должно быть взаимосвязано. 8c10247f75e3001d41cd03768e46005ba7dfb40f явно можно было разбить на пару отдельных коммитов поменьше - использование dbconn и игры с fetchall.

**Comment by Pin4uck** [comment]
"value = curs.fetchall()" - с ним пришлось намудрить потому что до того как я намудрил, выводилось два логинга одновременно. и я решил один из них под if поставить, но и прошлось размножить value

**Comment by ilyaevseev** [comment]
Смотрите внимательнее. value = curs.fetchall() при выполнении функции будет вызван дважды. В первый раз в if или else, во второй после else.

**Comment by Pin4uck** [comment]
точно, у себя правильно сделал, а сюда с ошибкой записал

**Comment by ilyaevseev** [comment]
Ещё ошибка:
```
raise LookupError
```
Должно быть:
```
raise LookupError(currency_name)
```

**Comment by ilyaevseev** [comment]
Вижу, что исправлено.

Используйте commit message с номером issue, например:

```
Fix #13: raise detailed LookupError with currency_name
```

Тогда Github будет автоматически вставлять в issue ссылку на исправляющий commit и закрывать issue.
