### ISSUE TITLE
В gitignore отсутствует .idea/

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/Bot_Testik#14]
В [.gitignore](../blob/main/.gitignore) почему-то нет строки .idea/

Из-за этого в репозиторий попал [.idea/workspace.xml](../tree/main/.idea)

**Comment by Pin4uck** [comment]
b8e5d463f8148a0798203e993f6006abbf0dcd0e
добавил

**Comment by ilyaevseev** [comment]
Отлично, вижу 4adb987b666e12ec36e1bebe21d22f459f0cb5cf

В идеале лучше было сделать их одним коммитом.

Git squash пока пробовать больше не будем.
