### ISSUE TITLE
Лишняя промежуточная переменная

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/Bot_Testik#15]
https://github.com/Pin4uck/Bot_Testik/blob/14c611e87d91848436b6e3fbb59df4b88bcc1419/pb.py#L25

### Сейчас плохо:
```
result = []
ccy_pattern = re.escape(ccy_pattern) + '.*'
for exc in load_exchange():
    if re.match(ccy_pattern, exc['Cur_Abbreviation'], re.IGNORECASE) is not None:
        result.append(exc)
return result[0]['Cur_OfficialRate']
```

### Так лучше:
```
ccy_pattern = re.escape(ccy_pattern) + '.*'
for exc in load_exchange():
    if re.match(ccy_pattern, exc['Cur_Abbreviation'], re.IGNORECASE) is not None:
        return exc['Cur_OfficialRate']
raise LookupError(ccy_pattern)
```

### Преимущества:

* исчезла промежуточная переменная result
* код сократился (на одну строку, но тем не менее)
* код стал быстрее - заканчиваем поиск после первого успеха, а не продолжаем до конца массива
* код стал понятнее - return вместо append, прямое использование exc вместо result[0], явный raise вместо неявного IndexError

**Comment by Pin4uck** [comment]
972459d291ae50e6198dc21fd17c23afae85a241
исправил
