### ISSUE TITLE
ex_code

### ISSUE THREAD

**Issue by Pin4uck** [Pin4uck/Bot_Testik#4]
https://github.com/Pin4uck/Bot_Testik/blob/2d0def5f28fbc833f7c1b0889d07f7ddf1d5b593/Bodybot.py#L76

не понимаю откуда в функции serialize_ex параметр ex_json

**Comment by ilyaevseev** [comment]
### Последовательность вызова функций и передачи параметров (в обратном порядке):

* serialize_ex вызывается из send_exchange_result
* send_exchange_result получает код валюты в параметре ex_code, передаёт его в get_exchange, получает от неё результат, сохраняет в переменную "ex", передаёт её в serialize_ex, которая видит её под именем ex_json
* send_exchange_result вызывается из get_ex_callback
* get_ex_callback получает запрос от пользователя, вырезает из строки всё, начиная с пятого символа, и передаёт в send_exchange_result
* get_ex_callback вызывается из iq_callback, которая зарегистрирована в качестве обработчика пользовательских сообщений

### Возможная причина непонимания:

* если одна функция передаёт другой переменную в качестве параметра, эта переменная не обязана иметь на вызывающей и вызываемой стороне одинаковые имена.
