### ISSUE TITLE
Надо давать коммитам осмысленные заголовки

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/Bot_Testik#5]
Сейчас PyCharm обзывает коммиты автоматически, например: "Update currency_try_except.py"

По такому названию трудно понять, что именно менялось.

Сравните, например:
* [свою историю коммитов](../commits) - по названиям не понять ничего
* и [коммиты в проекте Microsoft Terminal](https://github.com/microsoft/terminal/commits/main) - по названиям сразу понятен смысл изменений.

**Comment by Pin4uck** [comment]
Буду учитывать
