### ISSUE TITLE
Нет предварительной проверки, что массив result удалось заполнить

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/Bot_Testik#7]
https://github.com/Pin4uck/Bot_Testik/blob/987a916b42c612432963a39933127e3b13da6f2e/pb.py#L26

В случае неудачи массив будет пустым. Это надо проверять.

**Comment by Pin4uck** [comment]
здесь try - except нужен?

**Comment by ilyaevseev** [comment]
try ... except нужен не здесь, а в вызывающей функции.

Пример:
```
def func1(a): return a[0]
print(func1([2,3,4]))
print(func1([]))
```
Первый print напечатает "2", второй выдаст exception:
```
IndexError: list index out of range
```
То же самое произойдёт у вас в программе, если массив result почему-то не получится заполнить, при попытке обратиться к result[0]. Или если result[0] есть, но в нём по какой-то причине нет поля Cur_ID, Cur_Abbreviation или Cur_OfficialRate.

Возможно, для таких ситуаций имеет смысл предусмотреть разные варианты обработки (например, сигнализировать, что на сайте изменился формат данных и программу надо доработать), но для начала достаточно перехватывать их все одним общим try..except

**Comment by Pin4uck** [comment]
https://github.com/Pin4uck/Bot_Testik/blob/925ca55095302fbe889e8824c71b99a438c0eba9/pb.py#L23
можно ли так? либо отдельную функцию на проверку нужно. Не знаю подойдет ли такой способ для всех случаев(url)

**Comment by ilyaevseev** [comment]
Так плохо - генерируемый в качестве сигнала об ошибке exception перехватывается и вместо него возвращается строка:
* состояние ошибки всё равно надо обрабатывать в вызывающей функции
* отличать строку от массива труднее, чем отличать exception от массива

Я бы вообще не пытался перехватывать и обрабатывать exception внутри get_exchanges, потому что она не знает, как поступить в случае ошибки. Это знает только та функция, которая её вызывает, и поэтому try..except я бы поместил там.

**Comment by Pin4uck** [comment]
6500f64e53d660ca9786dc07c74dfee251ff8c55
Таким образом?

**Comment by Pin4uck** [comment]
6500f64e53d660ca9786dc07c74dfee251ff8c55
таким образом?

**Comment by ilyaevseev** [comment]
Нет.

1) перехватывать Exception надо, когда знаешь, ЧТО И КАК делать в случае ошибки. Пример - get_currency_rate перехватывает исключения из read_cached_currency_rate, чтобы вызвать get_currency_rate2. В get_network_currency_rate перехватывать исключение бессмысленно, т.к. у неё нет сценария поведения на случай ошибки.

2) В чём смысл перехватить exception, чтобы вернуть его как значение функции? Что с таким возвращённым значением будет делать get_currency_rate2 ? Передаст его в store_currency_rate, как сейчас? А та попытается записать в базу? А потом вернёт боту и тот попытается отправить его клиенту?

3) Вообще get_network_currency_rate в нынешнем виде выглядит ненужной обёрткой вокруг pb.get_exchanges. Возможно, имеет смысл полностью убрать get_network_currency_rate и вызывать pb.get_exchanges из get_currency_rate2 напрямую.

**Comment by Pin4uck** [comment]
0dc710c175a2ab62f4307702c44762e805cd4d4f
А теперь?

**Comment by ilyaevseev** [comment]
1) pb.get_exchanges должен швырять исключение, если не может вернуть результат (кстати, так сейчас и есть, потому что при пустом result обращение к result[0] будет сгенерировано автоматически)

2) поэтому проверять "if rate:" после её вызова не нужно (т.е. как было до коммита) - при ошибке она не станет возвращать ошибку через return, а швырнёт исключение и мы пролетим мимо следующих строк до except

3) нынешний вариант get_currency_rate2 написан в расчёте на то, что pb.get_exchanges возвращает ошибку через return, но реализован неверно - получив от pb.get_exchanges ошибку, он не зайдёт в "if rate" и не попадёт в except, т.е. вернёт не пойми что, которое будет обработано в вызывающей функции не пойми как.

**Comment by Pin4uck** [comment]
https://github.com/Pin4uck/Bot_Testik/blob/ea3f67b42b302795a331fa5a36443ac2aa497e5a/currency.py#L24
Мне нужно использовать raise после if?

**Comment by ilyaevseev** [comment]
Не нужно использовать ни if, ни raise:
```
def get_currency_rate2(currency_name):
    try:
        rate = pb.get_exchanges(currency_name)
        store_currency_rate(currency_name, rate)
        return rate
    except:
        return read_cached_currency_rate(currency_name)
```
Вот рабочая версия. Единственное, что изменилось - мы избавились от лишней обёртки вокруг pb.get_exchanges и вызываем её напрямую.

Имеет смысл проверить, что любые возможные ошибки внутри pb.get_exchanges, store_currency_rate, return read_cached_currency_rate будут приводить к генерации исключений.

**Comment by Pin4uck** [comment]
а я что-то сразу подумал, что если rate будет пустым, то оно запишет в таблицу и будет пустая ячейка

**Comment by Pin4uck** [comment]
bf3ed888e4462211848730e9a2e41c528e33352a

**Comment by ilyaevseev** [comment]
> а я что-то сразу подумал, что если rate будет пустым, то оно запишет в таблицу и будет пустая ячейка

А зачем нам записывать в таблицу пустую ячейку?
