### ISSUE TITLE
Отсутствует requirements.txt

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/Bot_Testik#9]
Нужен сам requirements, и нужно упоминание в README про "pip3 install -U requirements.txt"

https://www.jetbrains.com/help/pycharm/managing-dependencies.html

**Comment by Pin4uck** [comment]
как правильно упомянуть это в реадме - в подзаголовке "как запустить"?
"pip3 install -U requirements.txt"

**Comment by ilyaevseev** [comment]
Команда верная, но должна быть в разделе "Как установить".

**Comment by Pin4uck** [comment]
Отредактировал реадме

**Comment by ilyaevseev** [comment]
Надо указать в issue исправляющие коммиты, чтобы их не требовалось искать в [списке коммитов](../commits) вручную:
* 32ca55dd17e31935524b67a2893973824bf397ce
* 818cd7a27650abb09d9c1e29d80976dc962c2395

Имело смысл склеить эти два мелких коммита в один большой через git squash. Операция для новичка нетривиальная, поэтому сейчас достаточно ограничиться чтением документации:
* https://htmlacademy.ru/blog/boost/tools/how-to-squash-commits-and-why-it-is-needed -- общая теория
* https://stackoverflow.com/questions/26898511/how-to-combine-group-of-local-commits-to-single-push-in-idea -- применительно к PyCharm

**Comment by ilyaevseev** [comment]
Нынешний requirements.txt сгенерирован автоматически? **В нём явно не хватает sqlite3.** Вручную я бы сделал его таким:
```
pyTelegramBotAPI
requests
sqlite3
```

Остальное либо доустановится автоматически по зависимостям от этих трёх (idna, pytz, urllib3, chardet, certifi, ...), либо входит в стандартную библиотеку Питона (json, gettext, re, sys, os)

С указыванием версий есть плюсы и минусы у каждого из вариантов:
* вообще не указывать
* указывать строго через "=="
* указывать минимальную через ">="

**Comment by Pin4uck** [comment]
Да странно я и не посмотрел что нет sqlite3. У меня и в списке в пичарме его нет и работает все. Может из-за того, что у меня несколько интерпретаторов в пичарме, и в остальных там много модулей

**Comment by Pin4uck** [comment]
И не знаю какой установить чтобы в списке был, там нет названия просто sqlite3

**Comment by ilyaevseev** [comment]
### Такое впечатление, что модуль sqlite3 входит в стандартную поставку Питона:

* в Ubuntu он находится в каталоге /usr/lib/python3.6/sqlite3/ и установлен из пакета libpython3.6-stdlib
* в https://www.sqlitetutorial.net/sqlite-python/ написано "PySQLite is a part of the Python Standard library since Python version 2.5"
* судя по URL в официальной документации, sqlite3 является не самостоятельным модулем, а частью стандартной библиотеки: https://docs.python.org/3/library/sqlite3.html

Задачу закрываю. Git squash отложим на будущее.
